# Generated by Django 3.1.7 on 2021-03-23 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('History_File', models.ImageField(blank=True, upload_to='History_Files/%Y/%m/%d/', verbose_name='Изображение пользователя для обработки')),
                ('History_Voice', models.FileField(blank=True, upload_to='History_Voices/', verbose_name='Аудиофайл пользователя для прослушивания')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
