# Generated by Django 3.1.7 on 2021-04-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='History_File',
            field=models.ImageField(blank=True, upload_to='History_Files/%Y/%m/%d/'),
        ),
    ]
