# Generated by Django 3.1.7 on 2021-03-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_01', '0002_user_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='History_File',
            field=models.ImageField(blank=True, upload_to='History_Files/% Y/% m/% d/', verbose_name='Файл истории пользователя'),
        ),
    ]
