# Generated by Django 3.1.7 on 2021-04-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_01', '0002_auto_20210414_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_history',
            name='History_File',
            field=models.ImageField(blank=True, upload_to='History_Files/%Y/%m/%d/', verbose_name='Изображение для чтения текста'),
        ),
    ]
